### ISSUE TITLE
"Plugin failed to ServeHTTP" Errors with v3.1.1

### ISSUE THREAD

**Issue by moschlar** [blindsidenetworks/mattermost-plugin-bigbluebutton#158]
Hi there,

I just installed v3.1.1 and now I'm seeing lots of
```
2021-06-22_08:55:47.03798 {"level":"error","ts":1624352147.0378995,"caller":"mlog/log.go:232","msg":"Plugin failed to ServeHTTP, RPC call failed","plugin_id":"bigbluebutton","error":"connection is shut down"}
2021-06-22_08:55:52.03819 {"level":"error","ts":1624352152.0381186,"caller":"mlog/log.go:232","msg":"Plugin failed to ServeHTTP, muxBroker couldn't Accept request body connection","plugin_id":"bigbluebutton","error":"timeout waiting for accept"}
2021-06-22_08:55:52.03826 {"level":"error","ts":1624352152.0381165,"caller":"mlog/log.go:232","msg":"Plugin failed to ServeHTTP, muxBroker couldn't accept connection","plugin_id":"bigbluebutton","serve_http_stream_id":2,"error":"timeout waiting for accept"}
```
What can cause this?

Regards,
Moritz

**Comment by harshilsharma63** [comment]
Hi @moschlar ,

seems like the plugin is crashing for you for some reason. Can you restart the plugin and monitor the logs to see why the plugin crashed in the first place?

**Comment by moschlar** [comment]
There's no error before the first line of that error...

Just the usual many lines of
```
2021-06-24_20:11:48.17026 {"level":"info","ts":1624565508.1701915,"caller":"mlog/sugar.go:21","msg":"Successfully got recordings info","plugin_id":"bigbluebutton"}
```

:thinking:

**Comment by moschlar** [comment]
Ah wait, loglevel was not `DEBUG`...

Now I got:
```
2021-06-24_20:15:30.21101 2021-06-24T22:15:30.210+0200	info	mlog/sugar.go:21	Successfully got recordings info	{"plugin_id": "bigbluebutton"}
2021-06-24_20:15:30.22238 2021-06-24T22:15:30.220+0200	debug	plugin/hclog_adapter.go:54	panic: runtime error: invalid memory address or nil pointer dereference	{"plugin_id": "bigbluebutton"}
2021-06-24_20:15:30.22241 2021-06-24T22:15:30.221+0200	debug	plugin/hclog_adapter.go:54	[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf8b18c]	{"plugin_id": "bigbluebutton"}
2021-06-24_20:15:30.22242 2021-06-24T22:15:30.221+0200	debug	plugin/hclog_adapter.go:54		{"plugin_id": "bigbluebutton"}
2021-06-24_20:15:30.22242 2021-06-24T22:15:30.221+0200	debug	plugin/hclog_adapter.go:54	goroutine 21 [running]:	{"plugin_id": "bigbluebutton"}
2021-06-24_20:15:30.22242 2021-06-24T22:15:30.221+0200	debug	plugin/hclog_adapter.go:54	main.(*Plugin).Loopthroughrecordings(0xc000297590)	{"plugin_id": "bigbluebutton"}
2021-06-24_20:15:30.22244 2021-06-24T22:15:30.221+0200	debug	plugin/hclog_adapter.go:54		/Users/harshilsharma/codebase/go/src/github.com/blindsightnetworks/mattermost-plugin-bigbluebutton/server/responsehandlers.go:79 +0x2ac	{"plugin_id": "bigbluebutton"}
2021-06-24_20:15:30.22245 2021-06-24T22:15:30.221+0200	debug	plugin/hclog_adapter.go:54	github.com/mattermost/mattermost-plugin-api/cluster.(*Job).run.func1(0xc0004325a0, 0xc00043df00)	{"plugin_id": "bigbluebutton"}
2021-06-24_20:15:30.22246 2021-06-24T22:15:30.221+0200	debug	plugin/hclog_adapter.go:54		/Users/harshilsharma/codebase/go/src/github.com/blindsightnetworks/mattermost-plugin-bigbluebutton/vendor/github.com/mattermost/mattermost-plugin-api/cluster/job.go:204 +0x4af	{"plugin_id": "bigbluebutton"}
2021-06-24_20:15:30.22246 2021-06-24T22:15:30.221+0200	debug	plugin/hclog_adapter.go:54	github.com/mattermost/mattermost-plugin-api/cluster.(*Job).run(0xc0004325a0)	{"plugin_id": "bigbluebutton"}
2021-06-24_20:15:30.22247 2021-06-24T22:15:30.221+0200	debug	plugin/hclog_adapter.go:54		/Users/harshilsharma/codebase/go/src/github.com/blindsightnetworks/mattermost-plugin-bigbluebutton/vendor/github.com/mattermost/mattermost-plugin-api/cluster/job.go:214 +0x185	{"plugin_id": "bigbluebutton"}
2021-06-24_20:15:30.22247 2021-06-24T22:15:30.221+0200	debug	plugin/hclog_adapter.go:54	created by github.com/mattermost/mattermost-plugin-api/cluster.Schedule	{"plugin_id": "bigbluebutton"}
2021-06-24_20:15:30.22248 2021-06-24T22:15:30.221+0200	debug	plugin/hclog_adapter.go:54		/Users/harshilsharma/codebase/go/src/github.com/blindsightnetworks/mattermost-plugin-bigbluebutton/vendor/github.com/mattermost/mattermost-plugin-api/cluster/job.go:130 +0x3e5	{"plugin_id": "bigbluebutton"}
2021-06-24_20:15:30.22256 2021-06-24T22:15:30.222+0200	debug	plugin/hclog_adapter.go:52	plugin process exited	{"plugin_id": "bigbluebutton", "wrapped_extras": "path/var/opt/gitlab/mattermost/plugins/bigbluebutton/server/plugin.exepid11776errorexit status 2"}
```

**Comment by moschlar** [comment]
Deleting all the `pluginid=bigbluebutton` from the database makes the issue go away for now...

**Comment by moschlar** [comment]
@harshilsharma63 are there any more steps I can perform to help you debug the problem?

**Comment by moschlar** [comment]
I deleted all rows for the plugin from the key value store in the database and for some minutes now it seems to be running fine...

**Comment by moschlar** [comment]
And again - something with the recordings goes terribly wrong after some time:

```
2021-07-03_12:36:00.08548 2021-07-03T14:36:00.085+0200	info	mlog/sugar.go:21	[{"RecordID":"87909aba78e7c49c7ee4d9a5996868e1459a8d54-1625314293996","MeetingID":"1unvi7EshpE0aYiVbAH9622mifF","Name":"Holz-Café","Published":"true","State":"published","StartTime":"1625314293996","EndTime":"1625314311097","Participants":"1","MetaData":{"Title":"","Subject":"","Description":"","Creator":"","Contributor":"","Language":""},"Playback":{"Format":[{"Type":"presentation","Url":"https://scalelite..../playback/presentation/2.3/87909aba78e7c49c7ee4d9a5996868e1459a8d54-1625314293996","Length":"0","Images":["https://scalelite..../presentation/87909aba78e7c49c7ee4d9a5996868e1459a8d54-1625314293996/presentation/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1625314294016/thumbnails/thumb-3.png","https://scalelite..../presentation/87909aba78e7c49c7ee4d9a5996868e1459a8d54-1625314293996/presentation/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1625314294016/thumbnails/thumb-2.png","https://scalelite..../presentation/87909aba78e7c49c7ee4d9a5996868e1459a8d54-1625314293996/presentation/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1625314294016/thumbnails/thumb-1.png"]}]}}]	{"plugin_id": "bigbluebutton"}
2021-07-03_12:36:00.17244 2021-07-03T14:36:00.172+0200	debug	plugin/hclog_adapter.go:54	panic: runtime error: invalid memory address or nil pointer dereference	{"plugin_id": "bigbluebutton"}
2021-07-03_12:36:00.17247 2021-07-03T14:36:00.172+0200	debug	plugin/hclog_adapter.go:54	[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf8b18c]	{"plugin_id": "bigbluebutton"}
2021-07-03_12:36:00.17247 2021-07-03T14:36:00.172+0200	debug	plugin/hclog_adapter.go:54		{"plugin_id": "bigbluebutton"}
2021-07-03_12:36:00.17247 2021-07-03T14:36:00.172+0200	debug	plugin/hclog_adapter.go:54	goroutine 45 [running]:	{"plugin_id": "bigbluebutton"}
2021-07-03_12:36:00.17248 2021-07-03T14:36:00.172+0200	debug	plugin/hclog_adapter.go:54	main.(*Plugin).Loopthroughrecordings(0xc000297590)	{"plugin_id": "bigbluebutton"}
2021-07-03_12:36:00.17248 2021-07-03T14:36:00.172+0200	debug	plugin/hclog_adapter.go:54		/Users/harshilsharma/codebase/go/src/github.com/blindsightnetworks/mattermost-plugin-bigbluebutton/server/responsehandlers.go:79 +0x2ac	{"plugin_id": "bigbluebutton"}
2021-07-03_12:36:00.17251 2021-07-03T14:36:00.172+0200	debug	plugin/hclog_adapter.go:54	github.com/mattermost/mattermost-plugin-api/cluster.(*Job).run.func1(0xc00049f8c0, 0xc0005b7f00)	{"plugin_id": "bigbluebutton"}
2021-07-03_12:36:00.17252 2021-07-03T14:36:00.172+0200	debug	plugin/hclog_adapter.go:54		/Users/harshilsharma/codebase/go/src/github.com/blindsightnetworks/mattermost-plugin-bigbluebutton/vendor/github.com/mattermost/mattermost-plugin-api/cluster/job.go:204 +0x4af	{"plugin_id": "bigbluebutton"}
2021-07-03_12:36:00.17252 2021-07-03T14:36:00.172+0200	debug	plugin/hclog_adapter.go:54	github.com/mattermost/mattermost-plugin-api/cluster.(*Job).run(0xc00049f8c0)	{"plugin_id": "bigbluebutton"}
2021-07-03_12:36:00.17253 2021-07-03T14:36:00.172+0200	debug	plugin/hclog_adapter.go:54		/Users/harshilsharma/codebase/go/src/github.com/blindsightnetworks/mattermost-plugin-bigbluebutton/vendor/github.com/mattermost/mattermost-plugin-api/cluster/job.go:214 +0x185	{"plugin_id": "bigbluebutton"}
2021-07-03_12:36:00.17253 2021-07-03T14:36:00.172+0200	debug	plugin/hclog_adapter.go:54	created by github.com/mattermost/mattermost-plugin-api/cluster.Schedule	{"plugin_id": "bigbluebutton"}
2021-07-03_12:36:00.17253 2021-07-03T14:36:00.172+0200	debug	plugin/hclog_adapter.go:54		/Users/harshilsharma/codebase/go/src/github.com/blindsightnetworks/mattermost-plugin-bigbluebutton/vendor/github.com/mattermost/mattermost-plugin-api/cluster/job.go:130 +0x3e5	{"plugin_id": "bigbluebutton"}
2021-07-03_12:36:00.17451 2021-07-03T14:36:00.174+0200	debug	plugin/hclog_adapter.go:52	plugin process exited	{"plugin_id": "bigbluebutton", "wrapped_extras": "path/var/opt/gitlab/mattermost/plugins/bigbluebutton/server/plugin.exepid136221errorexit status 2"}
```

**Comment by harshilsharma63** [comment]
@moschlar when you deleted the rows from the database, did you also restart the plugin?

Let's schedule a quick call to debug this. I've sent you an email for the same. Please check it out.

**Comment by moschlar** [comment]
@harshilsharma63 
> @moschlar when you deleted the rows from the database, did you also restart the plugin?

Yes, I disabled it beforehand, restarted Mattermost, deleted the rows, and then enable it again.

**Comment by harshilsharma63** [comment]
@moschlar please use the latest [v3.2.0 release](https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/releases/tag/v3.2.0) until we fix the cluster issue.

**Comment by moschlar** [comment]
I just installed it - let’s see how it goes!

**Comment by moschlar** [comment]
Looking good so far!

**Comment by harshilsharma63** [comment]
@moschlar what version of Scalite are you running?

**Comment by moschlar** [comment]
@harshilsharma63 I think that's 1.1.5.1 but maybe @christmart can clarify on that

**Comment by harshilsharma63** [comment]
@christmart any idea?
