### ISSUE TITLE
Error on plugin activation. Mattermost 5.35.4

### ISSUE THREAD

**Issue by taupasse** [blindsidenetworks/mattermost-plugin-bigbluebutton#206]
Hello,

when i try to activate the plugin, it seems to work in system console, but nothing happens in frontend.
I have the bigbluebutton icon on the top right, but submenu is almost empty, not corresponding to the chosen options in plugin configuration.

In debug log : 

`{"level":"debug","ts":1643986698.0813618,"caller":"plugin/hclog_adapter.go:52","msg":"starting plugin","plugin_id":"bigbluebutton","wrapped_extras":"path/var/opt/gitlab/mattermost/plugins/bigbluebutton/server/plugin.exeargs[/var/opt/gitlab/mattermost/plugins/bigbluebutton/server/plugin.exe]"}
{"level":"debug","ts":1643986698.083251,"caller":"plugin/hclog_adapter.go:52","msg":"plugin started","plugin_id":"bigbluebutton","wrapped_extras":"path/var/opt/gitlab/mattermost/plugins/bigbluebutton/server/plugin.exepid15790"}
{"level":"debug","ts":1643986698.083291,"caller":"plugin/hclog_adapter.go:52","msg":"waiting for RPC address","plugin_id":"bigbluebutton","wrapped_extras":"path/var/opt/gitlab/mattermost/plugins/bigbluebutton/server/plugin.exe"}
{"level":"debug","ts":1643986698.1002584,"caller":"plugin/hclog_adapter.go:52","msg":"plugin address","plugin_id":"bigbluebutton","wrapped_extras":"networkunixaddress/tmp/plugin317356460timestamp2022-02-04T15:58:18.099+0100"}
{"level":"debug","ts":1643986698.1003568,"caller":"plugin/hclog_adapter.go:52","msg":"using plugin","plugin_id":"bigbluebutton","wrapped_extras":"version1"}
{"level":"error","ts":1643986703.106694,"caller":"mlog/log.go:247","msg":"RPC call to OnActivate plugin failed.","plugin_id":"bigbluebutton","error":"EOF"}
{"level":"debug","ts":1643986703.1669354,"caller":"plugin/hclog_adapter.go:54","msg":"panic: runtime error: invalid memory address or nil pointer dereference","plugin_id":"bigbluebutton"}
{"level":"debug","ts":1643986703.166986,"caller":"plugin/hclog_adapter.go:54","msg":"[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xfb0770]","plugin_id":"bigbluebutton"}
{"level":"debug","ts":1643986703.1669972,"caller":"plugin/hclog_adapter.go:54","msg":"","plugin_id":"bigbluebutton"}
{"level":"debug","ts":1643986703.1670046,"caller":"plugin/hclog_adapter.go:54","msg":"goroutine 11 [running]:","plugin_id":"bigbluebutton"}
{"level":"debug","ts":1643986703.1670125,"caller":"plugin/hclog_adapter.go:54","msg":"main.(*Plugin).OnConfigurationChange(0xc000123b00, 0x0, 0x0)","plugin_id":"bigbluebutton"}
{"level":"debug","ts":1643986703.16702,"caller":"plugin/hclog_adapter.go:54","msg":"\tgithub.com/blindsidenetworks/mattermost-plugin-bigbluebutton/server/config.go:46 +0x90","plugin_id":"bigbluebutton"}
{"level":"debug","ts":1643986703.167039,"caller":"plugin/hclog_adapter.go:54","msg":"github.com/mattermost/mattermost-server/v5/plugin.(*hooksRPCServer).OnConfigurationChange(0xc000072340, 0x17bfbd0, 0xc0000306b0, 0x0, 0x0)","plugin_id":"bigbluebutton"}`

thanks for your help.

**Comment by taupasse** [comment]
I can add that /bbb command is not working. It says that command was not found.

**Comment by harshilsharma63** [comment]
@taupasse did you try the latest v4.3.1?
