### ISSUE TITLE
No action on "Join meeting"

### ISSUE THREAD

**Issue by thomas-mc-work** [blindsidenetworks/mattermost-plugin-bigbluebutton#231]
**Describe the bug**

Sometimes after creating a room a click on "Join Room" doesn't open the conference in a separate Tab/Window as expected. I can then still join using the link that is created below in the chat.

**To Reproduce**

1. Create a Room in a channel
2. Click on the 'Join Meeting' Button

**Expected behavior**

Expected: Join the room in a new window, but nothing happens

**Environment:**
 - Mattermost version: [e.g. v6.1]
 - Plugin version [e.g v4.3.0]

**Additional context**

A failed request from the network tab of the developer tools (exported as Fetch command):

    await fetch("https://mattermost.mydomain.org/api/v4/users/status/ids", {
        "credentials": "include",
        "headers": {
            "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:106.0) Gecko/20100101 Firefox/106.0",
            "Accept": "*/*",
            "Accept-Language": "en",
            "X-Requested-With": "XMLHttpRequest",
            "X-CSRF-Token": "tr7ier4bi3gj9nn8hrmu5tq6aw",
            "Content-Type": "application/json",
            "Sec-Fetch-Dest": "empty",
            "Sec-Fetch-Mode": "cors",
            "Sec-Fetch-Site": "same-origin",
            "Sec-GPC": "1",
            "Pragma": "no-cache",
            "Cache-Control": "no-cache"
        },
        "body": "[\"\"]",
        "method": "POST",
        "mode": "cors"
    });

**Respone:**

Status code: 400

     {"id":"api.context.invalid_body_param.app_error","message":"Invalid or missing user_ids in request body.","detailed_error":"","request_id":"6f17szs86jboxe955ckck8erzc","status_code":400}

**Comment by thomas-mc-work** [comment]
There seem to be two different issues:

- open the session in a new tab: that was my fault. My browser blocked the popups, so here is no issue
- the failed request: this one still persists

**Comment by procitec-it** [comment]
Hi,

we have a similar issue. we are using mattermost 9.11.6. with nginx as reverse proxy in front of it, and want to use the bigbluebutton plugin v4.4.0 in mattermost.
bbb was installed by the installer script currently running with greenlight-v3. bbb as a standalone solution is working fine, and i was able to integrate the plugin into mattermost and set everything up as described.

now we get to the problem: if i use the plugin to create a meeting in bbb, i get the message from the bot, but, when i want to join the meeting, its stuck on "Generating meeting link..."

If i try to reach the bbb api from my mattermost server shell via curl this works just fine, but i get the following errors in the developer console, if i try to start a meeting via the mattermost plugin:

/api/v4/users/undefined:1 
        
        
Failed to load resource: the server responded with a status of 400
bigbluebutton_278bb1e9fee1899c_bundle.js:42494 Uncaught (in promise) Error: Ungültiger oder fehlender user_id Parameter in Anfrage-URL.
    at new ClientError (bigbluebutton_278bb1e9fee1899c_bundle.js:42494:28)
    at Client4.<anonymous> (bigbluebutton_278bb1e9fee1899c_bundle.js:42153:31)
    at step (bigbluebutton_278bb1e9fee1899c_bundle.js:5874:23)
    at Object.next (bigbluebutton_278bb1e9fee1899c_bundle.js:5855:53)
    at fulfilled (bigbluebutton_278bb1e9fee1899c_bundle.js:5845:58)Understand this errorAI
/api/v4/posts/rwqrhi31w3nxzp3tgh3smk1tqc/actions/bigBlueButtonJoinMeeting:1 
        
Failed to load resource: the server responded with a status of 400 ()


any suggestions? iam glad for any help.

kind regards
