### ISSUE TITLE
Can't view recordings in mattermost channel

### ISSUE THREAD

**Issue by rabser** [blindsidenetworks/mattermost-plugin-bigbluebutton#72]
Hi, i read the other issues related to recordings problems, but none of them seems apply.
I've a BBB new installation finished 10 hours ago - latest release - and i connected it to my mattermost.
The BBB rooms works perfectly and the recordings seems ok, if i take  a look at the log i got:

```
I, [2020-03-23T01:48:13.029530 #87718]  INFO -- : Making callback for recording ready notification
I, [2020-03-23T01:48:13.032745 #87718]  INFO -- : Sending request to https://mymattermost/plugins/bigbluebutton/recordingready
I, [2020-03-23T01:48:13.045159 #87718]  INFO -- : Recording notifier successful: f05543d78bdaacd93xxxxxxx093c0392ccbaee8db-1584924228700 (code 200)
I, [2020-03-23T01:48:13.045246 #87718]  INFO -- : Recording Ready notify ends
```

where i changed for security my mattermost url and the recording id.
But no recordings appears into the mattermost thread: some hints on how to understand what it's happening ?

**Comment by rabser** [comment]
It seems that on this server (please note that other mattermost installation i own works fine) the mattermost plugin for bigbluebutton encouter a bug, these are the log lines i got after ending a conference and the recording (very short) it's available:

```
2020-03-28_02:41:15.08088 {"level":"info","ts":1585363275.0808544,"caller":"mlog/sugar.go:19","msg":"Successfully got recordings info","plugin_id":"bigbluebutton"}
2020-03-28_02:41:15.08822 {"level":"info","ts":1585363275.0881946,"caller":"mlog/sugar.go:19","msg":"Successfully got recordings info","plugin_id":"bigbluebutton"}
2020-03-28_02:41:15.10297 {"level":"info","ts":1585363275.1029391,"caller":"mlog/sugar.go:19","msg":"Successfully got recordings info","plugin_id":"bigbluebutton"}
2020-03-28_02:41:15.10446 {"level":"info","ts":1585363275.104424,"caller":"go-plugin@v1.0.1/stream.go:15","msg":"2020/03/28 03:41:15 cron: panic running job: runtime error: invalid memory address or nil pointer dereference","plugin_id":"bigbluebutton","source":"plugin_stderr"}
2020-03-28_02:41:15.10447 {"level":"info","ts":1585363275.104453,"caller":"go-plugin@v1.0.1/stream.go:15","msg":"goroutine 77 [running]:","plugin_id":"bigbluebutton","source":"plugin_stderr"}
2020-03-28_02:41:15.10448 {"level":"info","ts":1585363275.1044605,"caller":"go-plugin@v1.0.1/stream.go:15","msg":"github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/server/vendor/github.com/robfig/cron.(*Cron).runWithRecovery.func1(0xc000324140)","plugin_id":"bigbluebutton","source":"plugin_stderr"}
2020-03-28_02:41:15.10449 {"level":"info","ts":1585363275.1044667,"caller":"go-plugin@v1.0.1/stream.go:15","msg":"\t/Users/harshilsharma/codebase/go/src/github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/server/vendor/github.com/robfig/cron/cron.go:161 +0xbc","plugin_id":"bigbluebutton","source":"plugin_stderr"}
2020-03-28_02:41:15.10449 {"level":"info","ts":1585363275.1044729,"caller":"go-plugin@v1.0.1/stream.go:15","msg":"panic(0xd8c5a0, 0x1508ac0)","plugin_id":"bigbluebutton","source":"plugin_stderr"}
2020-03-28_02:41:15.10451 {"level":"info","ts":1585363275.1044784,"caller":"go-plugin@v1.0.1/stream.go:15","msg":"\t/usr/local/Cellar/go/1.13.3/libexec/src/runtime/panic.go:679 +0x1e0","plugin_id":"bigbluebutton","source":"plugin_stderr"}
2020-03-28_02:41:15.10451 {"level":"info","ts":1585363275.1044838,"caller":"go-plugin@v1.0.1/stream.go:15","msg":"main.(*Plugin).Loopthroughrecordings(0xc000240bd0)","plugin_id":"bigbluebutton","source":"plugin_stderr"}
2020-03-28_02:41:15.10452 {"level":"info","ts":1585363275.1044898,"caller":"go-plugin@v1.0.1/stream.go:15","msg":"\t/Users/harshilsharma/codebase/go/src/github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/server/responsehandlers.go:562 +0x66d","plugin_id":"bigbluebutton","source":"plugin_stderr"}
2020-03-28_02:41:15.10453 {"level":"info","ts":1585363275.1044955,"caller":"go-plugin@v1.0.1/stream.go:15","msg":"github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/server/vendor/github.com/robfig/cron.FuncJob.Run(0xc00001e850)","plugin_id":"bigbluebutton","source":"plugin_stderr"}
2020-03-28_02:41:15.10453 {"level":"info","ts":1585363275.104501,"caller":"go-plugin@v1.0.1/stream.go:15","msg":"\t/Users/harshilsharma/codebase/go/src/github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/server/vendor/github.com/robfig/cron/cron.go:92 +0x25","plugin_id":"bigbluebutton","source":"plugin_stderr"}
2020-03-28_02:41:15.10454 {"level":"info","ts":1585363275.1045086,"caller":"go-plugin@v1.0.1/stream.go:15","msg":"github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/server/vendor/github.com/robfig/cron.(*Cron).runWithRecovery(0xc000324140, 0xf74260, 0xc00001e850)","plugin_id":"bigbluebutton","source":"plugin_stderr"}
2020-03-28_02:41:15.10456 {"level":"info","ts":1585363275.1045144,"caller":"go-plugin@v1.0.1/stream.go:15","msg":"\t/Users/harshilsharma/codebase/go/src/github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/server/vendor/github.com/robfig/cron/cron.go:165 +0x65","plugin_id":"bigbluebutton","source":"plugin_stderr"}
2020-03-28_02:41:15.10456 {"level":"info","ts":1585363275.1045208,"caller":"go-plugin@v1.0.1/stream.go:15","msg":"created by github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/server/vendor/github.com/robfig/cron.(*Cron).run","plugin_id":"bigbluebutton","source":"plugin_stderr"}
2020-03-28_02:41:15.10458 {"level":"info","ts":1585363275.1045258,"caller":"go-plugin@v1.0.1/stream.go:15","msg":"\t/Users/harshilsharma/codebase/go/src/github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/server/vendor/github.com/robfig/cron/cron.go:199 +0x5e9","plugin_id":"bigbluebutton","source":"plugin_stderr"}

```
I tried also to uninstall/install again the latest release of the plugin, but without luck.
My Mattermost version is 5.20.1 hosted on a centos linux box.

**Comment by eyebank** [comment]
@rabser I noticed the same or similair issue with the plugin. Recording do not appear in the channel. I build several servers with the script and manually same result. 
However, with the same servers with the greenlight front end the recordings appear.

**Comment by gppcff** [comment]
I have the same problem.
From what I see [in the code](https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/blob/54386cddbee0278a47d6dd0eb45e794c90d99fd6/server/responsehandlers.go#L382), for some reason, the management of the RecordingReady endpoint has been commented and the "status_recording" is not set to "COMPLETE", consequently[ the links to the recordings](https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/blob/54386cddbee0278a47d6dd0eb45e794c90d99fd6/webapp/components/post_type_bbb/post_type_bbb.jsx#L367) are not show.

Am I wrong ???

**Comment by harshilsharma63** [comment]
This is fixed in the newer releases. Please upgrade to the latest version. Feel free to re-open this issue if it still doesn't work for you.
